---
version: '2.0'
services:
  ollama:
    image: ollama/ollama
    expose:
      - port: 11434
        as: 11434
        to:
          - global: true
    command:
      - 'bash'
      - '-c'
    args:
      - 'ollama serve > /dev/null 2>&1 & sleep 10 && ollama pull mistral && sleep infinity;'
      # replace 