---
version: '2.0'
services:
  ollama:
    image: ollama/ollama
    expose:
      - port: 11434
        as: 11434
        to:
          - global: true
    command:
      - 'bash'
      - '-c'
    args:
      - 'ollama serve > /dev/null 2>&1 & sleep 10 && ollama pull mistral && sleep infinity;'
      # replace mistral with any other dataset you want to pull on first start
profiles:
  compute:
    ollama:
      resources:
        cpu:
          units: 12
        memory:
          size: 16Gi
        storage:
          - size: 50Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - A100
  placement:
    dcloud:
      pricing:
        ollama:
          denom: uakt
          amount: 1000
deployment:
  ollama:
    dcloud:
      profile: ollama
      count: 1
